# Generated by Django 4.2.13 on 2024-06-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_historia_samochodow', '0004_rename_recommedations_repair_recommendations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projekt_historia_samochodow.carowner'),
        ),
    ]
