# Generated by Django 4.2.13 on 2024-06-29 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_historia_samochodow', '0005_alter_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.AddField(
            model_name='car',
            name='year_of_production',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carowner',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt_historia_samochodow.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_of_fuel',
            field=models.CharField(choices=[(1, 'PB95'), (2, 'PB98'), (3, 'LPG+PB95'), (4, 'LPG+PB98'), (5, 'DIESEL')]),
        ),
    ]
