# Generated by Django 4.2.13 on 2024-06-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_historia_samochodow', '0006_remove_car_owner_car_year_of_production_carowner_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_of_production',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt_historia_samochodow.car'),
        ),
    ]
