# Generated by Django 4.2.13 on 2024-07-02 18:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_historia_samochodow', '0007_alter_car_year_of_production_alter_carowner_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[(1, 'Coupe'), (2, 'Hatchback'), (3, 'Kabriolet'), (4, 'Kombi'), (5, 'Minivan'), (6, 'Pickup'), (7, 'Sedan'), (8, 'SUV'), (9, 'Van')], verbose_name='Typ nadwozia'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photos',
            field=models.ImageField(upload_to='media/%Y/%m/%d/', verbose_name='Zdjęcia samochodu'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Kolor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_of_first_registration',
            field=models.DateField(verbose_name='Data pierwszej rejestracji'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_power_HP',
            field=models.PositiveSmallIntegerField(verbose_name='Moc silnika w KM'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_power_kW',
            field=models.PositiveSmallIntegerField(verbose_name='Moc silnika w kW'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.PositiveSmallIntegerField(verbose_name='Pojemność silnika'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(verbose_name='Przebieg'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=64, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_of_the_registration_certificate',
            field=models.CharField(max_length=15, verbose_name='Numer dowodu rejestracyjnego'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(max_length=15, verbose_name='Numer rejestracyjny'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_of_fuel',
            field=models.CharField(choices=[(1, 'PB95'), (2, 'PB98'), (3, 'LPG+PB95'), (4, 'LPG+PB98'), (5, 'DIESEL')], verbose_name='Rodzaj paliwa'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_of_production',
            field=models.PositiveSmallIntegerField(verbose_name='Data produkcji'),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt_historia_samochodow.car', verbose_name='Samochód'),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='date_of_repair',
            field=models.DateField(verbose_name='Data naprawy'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='mileage',
            field=models.PositiveIntegerField(verbose_name='Przebieg'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='part',
            field=models.CharField(max_length=64, verbose_name='Nazwa części'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='part_number',
            field=models.CharField(max_length=64, verbose_name='Numer części'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='recommendations',
            field=models.TextField(verbose_name='Zalecenia'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='type_of_repair',
            field=models.CharField(choices=[(1, 'Alternatory i akumulatory'), (2, 'Chłodzenie'), (3, 'Doloty powietrza'), (4, 'Filtry'), (5, 'Hamulce'), (6, 'Klimatyzacje i nagrzewnice'), (7, 'Lusterka'), (8, 'Nadwozie'), (9, 'Oleje i płyny'), (10, 'Opony i felgi'), (11, 'Paski klinowe i wielorowkowe'), (12, 'Przeguby, półosie i wały napędowe'), (13, 'Rozruch i zapłon'), (14, 'Rozrządy'), (15, 'Silniki i skrzynie biegów'), (16, 'Smarowanie'), (17, 'Sprzęgła'), (18, 'Układy kierownicze'), (19, 'Układy wtryskowe'), (20, 'Wycieraczki i szyby'), (21, 'Wydechy'), (22, 'Zasilanie paliwem'), (23, 'Zawieszenie i amortyzatory'), (24, 'Żarówki i oświetlenie')], verbose_name='Rodzaj naprawy'),
        ),
    ]
