# Generated by Django 4.2.13 on 2024-07-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_historia_samochodow', '0008_alter_car_body_type_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_photos',
            field=models.ImageField(upload_to='media', verbose_name='Zdjęcia samochodu'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.PositiveSmallIntegerField(verbose_name='Pojemność silnika (w cm3)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='repairs',
            field=models.ManyToManyField(blank=True, null=True, to='projekt_historia_samochodow.repair'),
        ),
    ]
