# Generated by Django 4.2.13 on 2024-07-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_historia_samochodow', '0011_alter_car_body_type_alter_car_type_of_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='VIN',
            field=models.CharField(max_length=17),
        ),
    ]
