# Generated by Django 4.2.13 on 2024-07-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_historia_samochodow', '0026_alter_repair_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.RemoveField(
            model_name='events',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='events',
            name='updated_at',
        ),
    ]
