# Generated by Django 4.2.13 on 2024-07-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_historia_samochodow', '0027_alter_events_options_remove_events_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='title',
        ),
    ]
