# Generated by Django 4.2.13 on 2024-07-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_historia_samochodow', '0028_rename_name_events_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
