# Generated by Django 4.2.13 on 2024-07-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_historia_samochodow', '0029_rename_events_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
